import test from 'node:test';
import assert from 'node:assert/strict';
import {RacingSimulation,NEUTRAL} from '../packages/client/racing-simulation.js';
import {gates,pickupSpawns} from '../packages/client/racing-track.js';
function race(){const s=new RacingSimulation();s.add('human');s.ready('human',true);assert(s.start('human'));for(let i=0;i<91;i++)s.step(1/30);return s;}
test('ready authority, frozen roster, fresh participant and capacity',()=>{const s=new RacingSimulation();for(let i=1;i<=4;i++)s.add('p'+i);assert.equal(s.add('p5'),null);assert.equal(s.start('p2'),false);for(let i=1;i<=4;i++)s.ready('p'+i,true);assert(s.start('p1'));assert.equal(s.ready('p1',false),false);s.remove('p2');s.add('fresh');assert(s.trucks.find(p=>p.id==='p2').bot);assert(!s.trucks.some(p=>p.id==='fresh'));});
test('invalid and stale inputs rejected, missing controls expire',()=>{const s=race(),p=s.trucks[0];assert.equal(s.input('human',{...NEUTRAL,seq:0,throttle:Infinity}),false);assert.equal(s.input('other',{...NEUTRAL,seq:0}),false);assert(s.input('human',{...NEUTRAL,seq:1,throttle:1}));assert.equal(s.input('human',{...NEUTRAL,seq:1}),false);for(let i=0;i<30;i++)s.step(1/30);assert.equal(p.ack,1);assert(p.inputAt<s.time-.3);assert(p.laps===0);});
test('ordered directional gates prevent skip/reverse and validate three laps',()=>{const s=race(),p=s.trucks[0];const cross=index=>{const g=gates[index];const old={x:g.x-g.tx,z:g.z-g.tz};p.x=g.x+g.tx;p.z=g.z+g.tz;s.checkpoint(p,old);};cross(0);assert.equal(p.laps,0);for(let lap=0;lap<3;lap++)for(const gate of [1,2,3,4,0])cross(gate);assert.equal(p.laps,3);assert.equal(p.checkpointCount,15);assert.equal(p.finish,s.raceTime);assert.equal(s.ranking()[0],p.id);});
test('recovery preserves progress and has bounded cooldown and penalty',()=>{const s=race(),p=s.trucks[0];p.checkpointCount=2;p.nextGate=3;s.recover(p);assert.equal(p.checkpointCount,2);assert.equal(p.nextGate,3);assert.equal(p.penalty,1.25);s.recover(p);assert.equal(p.penalty,1.25);assert.equal(p.vx,0);});
test('contested pickup has one owner, timed respawn and bounded nitro',()=>{const s=race();const item=s.pickups[0];for(const p of s.trucks){p.x=item.x;p.z=item.z;p.bot=false;p.nitro=0;}s.step(1/30);assert.equal(s.trucks.filter(p=>p.nitro>0).length,1);assert.equal(item.respawn,8);const t=s.trucks[0];t.nitro=4.9;item.respawn=0;t.x=item.x;t.z=item.z;s.trucks.slice(1).forEach(p=>p.x+=5);s.step(1/30);assert.equal(t.nitro,5);});
test('AI completes full replayable race within target duration and snapshots are independent',()=>{const s=race();s.trucks.forEach(p=>p.bot=true);for(let i=0;i<3600&&s.phase==='racing';i++)s.step(1/30);assert.equal(s.phase,'results');assert(s.trucks.some(p=>p.laps===3));assert(s.raceTime>=45&&s.raceTime<=90,s.raceTime);const snap=s.snapshot();snap.trucks[0].x=999;assert.notEqual(s.trucks[0].x,999);for(let i=0;i<241;i++)s.step(1/30);assert.equal(s.phase,'waiting');assert.equal(s.people.get('human').ready,false);});
test('hard timeout ends unfinished race and empty session clears trucks',()=>{const s=race();s.trucks.forEach(p=>p.bot=false);for(let i=0;i<3601;i++)s.step(1/30);assert.equal(s.phase,'results');assert(s.trucks.every(p=>p.finish===null));s.remove('human');assert.equal(s.phase,'waiting');assert.equal(s.trucks.length,0);});
